package com.neevtech.droolsweb.services.impl

import com.neevtech.droolsweb.model.UserBean;
import com.neevtech.droolsweb.model.ItemBean;
import com.neevtech.droolsweb.model.CurrentDateTime;
global org.apache.log4j.Logger logger;

rule "Insert CurrentDateTime in knowledge session"
salience 1

	when
		not CurrentDateTime()
		exists UserBean()
		exists ItemBean()
	then
		insert( new CurrentDateTime() );
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For US Location - 1st Occasion"
activation-group "US"

	when
		UserBean( location  == "US" )
		CurrentDateTime( date >= 10 && month == 8 || date <= 25 && month == 8 )
		$item: ItemBean()
	then
		$item.addDiscount(30);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For US Location - 2nd Occasion"

	when
		UserBean( location  == "US" )
		CurrentDateTime( date >= 13 && month == 5 || date <= 27 && month == 5 )
		$item: ItemBean()
	then
		$item.addDiscount(30);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For US Location - 3rd Occasion"
activation-group "US"

	when
		UserBean( location  == "US" )
		CurrentDateTime( date >= 12 && month == 8 || date <= 27 && month == 8 )
		$item: ItemBean()
	then
		$item.addDiscount(30);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For UK Location - 1st Occasion"

	when
		UserBean( location  == "UK" )
		CurrentDateTime( date >= 27 && month == 4 || date <= 11 && month == 5 )
		$item: ItemBean()
	then
		$item.addDiscount(20);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For UK Location - 2nd Occasion"

	when
		UserBean( location  == "UK" )
		CurrentDateTime( date >= 8 && month == 8 || date <= 23 && month == 8 )
		$item: ItemBean()
	then
		$item.addDiscount(20);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For UK Location - 3rd Occasion"

	when
		UserBean( location  == "UK" )
		CurrentDateTime( date >= 11 && month == 12 || date <= 25 && month == 12 )
		$item: ItemBean()
	then
		$item.addDiscount(20);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For INDIA Location - 1st Occasion"

	when
		UserBean( location  == "INDIA" )
		CurrentDateTime( date >= 25 && month == 4 || date <= 9 && month == 5 )
		$item: ItemBean()
	then
		$item.addDiscount(40);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For INDIA Location - 2nd Occasion"

	when
		UserBean( location  == "INDIA" )
		CurrentDateTime( date >= 15 && month == 7 || date <= 31 && month == 7 )
		$item: ItemBean()
	then
		$item.addDiscount(40);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "For INDIA Location - 3rd Occasion"

	when
		UserBean( location  == "INDIA" )
		CurrentDateTime( date >= 16 && month == 8 || date <= 1 && month == 9 )
		$item: ItemBean()
	then
		$item.addDiscount(40);
		logger.info("RuleName: "+ drools.getRule().getName());
end

rule "Retract facts from knowledge session"
salience -1

	when
		$currentDateTime: CurrentDateTime()
		$user: UserBean()
		$item: ItemBean()
	then
		retract( $currentDateTime );
		retract( $user );
		retract( $item );
		logger.info("RuleName: "+ drools.getRule().getName());
end
